import type { GameDef, ShopItem, TournamentDef } from "./types";

export const GAMES: GameDef[] = [
  {
    id: "crown-catch",
    title: "Crown Catch",
    tagline: "Attrapez l'or, évitez les pièges",
    category: "arcade",
    accent: "#d4af37",
    howTo: "Glissez le panier. Attrapez l’or, évitez les boules noires.",
    rules: [
      "Glissez le panier en bas de l’écran.",
      "Attrapez les pièces et couronnes d’or pour marquer.",
      "Une boule noire termine la partie.",
    ],
    perks: ["Réflexes et précision rapportent vite des points.", "Idéal pour enchaîner les missions du jour."],
  },
  {
    id: "reflex-ring",
    title: "Reflex Ring",
    tagline: "Tapez dans la zone d'or",
    category: "competitive",
    accent: "#f0d56a",
    howTo: "Touchez l’écran quand l’anneau est sur la zone d’or.",
    rules: [
      "L’anneau se resserre vers le centre.",
      "Touchez l’écran uniquement quand il est sur la zone d’or.",
      "Trop tôt ou trop tard : la série s’arrête.",
    ],
    perks: ["Parfait pour le classement compétitif.", "Un bon timing peut viser le palier x2 en mise."],
  },
  {
    id: "memory-vault",
    title: "Memory Vault",
    tagline: "Mémorisez les couronnes",
    category: "puzzle",
    accent: "#c9a227",
    howTo: "Retournez deux cartes identiques jusqu’à tout vider.",
    rules: [
      "Touchez une carte, puis une seconde.",
      "Deux symboles identiques disparaissent.",
      "Videz le coffre pour le meilleur score.",
    ],
    perks: ["Jeu calme, sans course contre la montre.", "Chaque paire fait monter couronnes et microns."],
  },
  {
    id: "orbit-dash",
    title: "Orbit Dash",
    tagline: "Survivez dans l'orbite",
    category: "action",
    accent: "#e8c547",
    howTo: "Touchez gauche / droite pour tourner. Prenez l’or, évitez les rochers.",
    rules: [
      "Touchez la gauche ou la droite pour changer d’orbite.",
      "Collectez l’or en mouvement.",
      "Un rocher = game over.",
    ],
    perks: ["Action rapide, scores élevés possibles.", "Bonne piste pour les mises et le Daily Cup."],
  },
  {
    id: "stack-king",
    title: "Stack King",
    tagline: "Empilez parfaitement",
    category: "casual",
    accent: "#d4af37",
    howTo: "Touchez pour poser chaque barre le plus au centre possible.",
    rules: [
      "Touchez pour poser la barre en mouvement.",
      "Plus elle est centrée, plus le combo monte.",
      "Un décalage trop grand fait tout s’écrouler.",
    ],
    perks: ["Simple à prendre en main.", "Les piles longues boostent couronnes et DGH."],
  },
  {
    id: "pulse-tap",
    title: "Pulse Tap",
    tagline: "Rythme et précision",
    category: "competitive",
    accent: "#f5d76e",
    howTo: "Appuyez sur la voie quand la barre d’or passe la ligne.",
    rules: [
      "Les barres d’or descendent sur trois voies.",
      "Touchez la voie au moment où la barre passe la ligne.",
      "Un raté casse le combo.",
    ],
    perks: ["Rythme soutenu, combo généreux.", "Très bon pour viser 600+ pts en mise."],
  },
  {
    id: "grid-merge",
    title: "Grid Merge",
    tagline: "Fusionnez les tuiles d'or",
    category: "puzzle",
    accent: "#b8962e",
    howTo: "Glissez pour fusionner les mêmes nombres.",
    rules: [
      "Glissez dans une direction pour déplacer les tuiles.",
      "Deux tuiles identiques fusionnent et marquent.",
      "La partie s’arrête quand la grille est bloquée.",
    ],
    perks: ["Stratégie : une partie peut durer et scorer fort.", "Les fusions hautes rapportent plus de couronnes."],
  },
  {
    id: "gold-slash",
    title: "Gold Slash",
    tagline: "Tranchez l'or en vol",
    category: "action",
    accent: "#d4af37",
    howTo: "Balayez les orbes d’or. Ne touchez pas les noirs.",
    rules: [
      "Balayez l’écran pour trancher les orbes d’or.",
      "Les orbes noirs sont interdits.",
      "Plus le combo est long, plus le score explose.",
    ],
    perks: ["Sensations arcade, parties courtes.", "Combo élevé = plus de microns sans mise."],
  },
  {
    id: "king-tap",
    title: "King Tap",
    tagline: "Combo de taps royaux",
    category: "casual",
    accent: "#f0d56a",
    howTo: "Tapez le plus vite possible pendant 15 secondes.",
    rules: [
      "Tapez le plus vite possible pendant 15 secondes.",
      "Chaque tap compte dans le combo.",
      "Le chronomètre termine la partie tout seul.",
    ],
    perks: ["Partie ultra courte, idéal entre deux missions.", "Score brut lié à votre vitesse."],
  },
  {
    id: "maze-crown",
    title: "Maze Crown",
    tagline: "Collectez avant le garde",
    category: "arcade",
    accent: "#c9a227",
    howTo: "Glissez pour bouger. Ramassez l’or avant le garde.",
    rules: [
      "Glissez pour déplacer le pion dans le labyrinthe.",
      "Ramassez l’or et la couronne.",
      "Le garde vous rattrape : partie terminée.",
    ],
    perks: ["Exploration + tension.", "Chaque collectible alimente score et microns."],
  },
  {
    id: "lane-rush",
    title: "Lane Rush",
    tagline: "Trois voies, un seul panier",
    category: "arcade",
    accent: "#d4af37",
    howTo: "Touchez gauche, centre ou droite. Prenez l’or, évitez les pièges.",
    rules: [
      "Touchez le tiers gauche, centre ou droit pour changer de voie.",
      "Attrapez les orbes d’or.",
      "Un piège noir termine la partie.",
    ],
    perks: ["Réflexes purs, parties rapides.", "Bonne source de microns sans mise."],
  },
  {
    id: "target-crown",
    title: "Target Crown",
    tagline: "Tapez l'or avant qu'il disparaisse",
    category: "action",
    accent: "#e8c547",
    howTo: "Touchez les cibles d’or. Évitez les noires. 5 or manqués = fin.",
    rules: [
      "Touchez uniquement les cibles d’or.",
      "Les cibles noires sont interdites.",
      "Cinq cibles d’or ratées terminent la partie.",
    ],
    perks: ["Précision et vitesse.", "Score élevé si vous enchaînez sans faute."],
  },
  {
    id: "gold-snake",
    title: "Gold Snake",
    tagline: "Grandissez, ne vous mordez pas",
    category: "arcade",
    accent: "#c9a227",
    howTo: "Touchez pour tourner. Mangez l’or, évitez les murs et votre corps.",
    rules: [
      "Touchez un côté de l’écran pour changer de direction.",
      "Mangez les blocs d’or pour grandir.",
      "Mur ou votre propre corps : partie terminée.",
    ],
    perks: ["Plus le serpent est long, plus le score explose.", "Classique addictif, idéal en mission."],
  },
  {
    id: "gap-flyer",
    title: "Gap Flyer",
    tagline: "Passez entre les piliers d'or",
    category: "action",
    accent: "#f0d56a",
    howTo: "Touchez pour voler. Passez dans l’ouverture, évitez les piliers.",
    rules: [
      "Touchez l’écran pour monter.",
      "Passez dans le trou entre les piliers d’or.",
      "Un choc ou le bord de l’écran termine la partie.",
    ],
    perks: ["Timing simple, difficulté croissante.", "Chaque pilier franchi rapporte gros."],
  },
  {
    id: "color-rush",
    title: "Color Rush",
    tagline: "Touchez la bonne couleur",
    category: "puzzle",
    accent: "#b8962e",
    howTo: "Touchez la couleur affichée avant la fin du temps. 3 vies.",
    rules: [
      "Regardez la couleur demandée en haut.",
      "Touchez le bouton de la même couleur.",
      "Trois erreurs ou temps écoulé : partie terminée.",
    ],
    perks: ["Aucune mise obligatoire.", "Le rythme accélère : plus de microns si vous tenez."],
  },
  {
    id: "simon-crown",
    title: "Simon Crown",
    tagline: "Reproduisez la séquence royale",
    category: "casual",
    accent: "#f5d76e",
    howTo: "Mémorisez la séquence allumée, puis rejouez-la dans l’ordre.",
    rules: [
      "Regardez les pads s’allumer.",
      "Rejouez exactement la même séquence.",
      "Une erreur termine la partie.",
    ],
    perks: ["Mémoire + combo.", "Chaque tour réussi allonge la séquence et le gain."],
  },
];

export const CATEGORIES: { id: "all" | GameDef["category"]; label: string }[] = [
  { id: "all", label: "Tous" },
  { id: "arcade", label: "Arcade" },
  { id: "puzzle", label: "Puzzle" },
  { id: "action", label: "Action" },
  { id: "competitive", label: "Compétitif" },
  { id: "casual", label: "Casual" },
];

export const TOURNAMENTS: TournamentDef[] = [
  {
    id: "daily-cup",
    title: "Daily Crown Cup",
    gameId: "reflex-ring",
    entryPi: 0,
    prizeLabel: "Couronnes + badge",
    durationHours: 24,
  },
  {
    id: "gold-clash",
    title: "Gold Clash",
    gameId: "crown-catch",
    entryPi: 0.1,
    prizeLabel: "Coffre d'or",
    durationHours: 48,
  },
  {
    id: "merge-masters",
    title: "Merge Masters",
    gameId: "grid-merge",
    entryPi: 0.05,
    prizeLabel: "Boost x2",
    durationHours: 36,
  },
  {
    id: "tap-throne",
    title: "Tap Throne",
    gameId: "king-tap",
    entryPi: 0.2,
    prizeLabel: "Couronne royale",
    durationHours: 72,
  },
];

export const SHOP: ShopItem[] = [
  {
    id: "tickets-5",
    name: "5 tickets tournoi",
    detail: "Accès immédiat aux coupes payantes",
    amount: 0.25,
    tickets: 5,
  },
  {
    id: "boost-1h",
    name: "Boost Couronne x2",
    detail: "Score doublé pendant 1 heure",
    amount: 0.1,
    boostMs: 60 * 60 * 1000,
  },
  {
    id: "lives-3",
    name: "Pack 3 vies",
    detail: "Continuez après un game over",
    amount: 0.05,
    lives: 3,
  },
  {
    id: "crown-200",
    name: "Pack 200 Couronnes",
    detail: "Progression de saison",
    amount: 0.2,
    crowns: 200,
  },
];

export function gameById(id: string) {
  return GAMES.find((g) => g.id === id);
}

export function gameCover(id: string) {
  return `/games/${id}.png`;
}
